// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contestant.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContestant = `-- name: CreateContestant :one
INSERT INTO contestants (name, birthday, nic_or_student_id, photo_url, gender, academic_year)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, COALESCE(birthday::text, '') AS birthday_text, nic_or_student_id, photo_url, gender, academic_year, created_at, updated_at
`

type CreateContestantParams struct {
	Name           string      `json:"name"`
	Birthday       pgtype.Date `json:"birthday"`
	NicOrStudentID string      `json:"nic_or_student_id"`
	PhotoUrl       *string     `json:"photo_url"`
	Gender         *string     `json:"gender"`
	AcademicYear   *string     `json:"academic_year"`
}

type CreateContestantRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	BirthdayText   interface{}        `json:"birthday_text"`
	NicOrStudentID string             `json:"nic_or_student_id"`
	PhotoUrl       *string            `json:"photo_url"`
	Gender         *string            `json:"gender"`
	AcademicYear   *string            `json:"academic_year"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateContestant(ctx context.Context, arg CreateContestantParams) (CreateContestantRow, error) {
	row := q.db.QueryRow(ctx, createContestant,
		arg.Name,
		arg.Birthday,
		arg.NicOrStudentID,
		arg.PhotoUrl,
		arg.Gender,
		arg.AcademicYear,
	)
	var i CreateContestantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthdayText,
		&i.NicOrStudentID,
		&i.PhotoUrl,
		&i.Gender,
		&i.AcademicYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContestant = `-- name: DeleteContestant :execrows
DELETE FROM contestants
WHERE id = $1
`

func (q *Queries) DeleteContestant(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContestant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listContestants = `-- name: ListContestants :many
SELECT id, name, COALESCE(birthday::text, '') AS birthday_text, nic_or_student_id, photo_url, gender, academic_year, created_at, updated_at
FROM contestants
ORDER BY created_at DESC
`

type ListContestantsRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	BirthdayText   interface{}        `json:"birthday_text"`
	NicOrStudentID string             `json:"nic_or_student_id"`
	PhotoUrl       *string            `json:"photo_url"`
	Gender         *string            `json:"gender"`
	AcademicYear   *string            `json:"academic_year"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListContestants(ctx context.Context) ([]ListContestantsRow, error) {
	rows, err := q.db.Query(ctx, listContestants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestantsRow{}
	for rows.Next() {
		var i ListContestantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BirthdayText,
			&i.NicOrStudentID,
			&i.PhotoUrl,
			&i.Gender,
			&i.AcademicYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContestant = `-- name: UpdateContestant :one
UPDATE contestants
SET
  name = $2,
  birthday = $3,
  nic_or_student_id = $4,
  photo_url = $5,
  gender = $6,
  academic_year = $7,
  updated_at = NOW()
WHERE id = $1
RETURNING id, name, COALESCE(birthday::text, '') AS birthday_text, nic_or_student_id, photo_url, gender, academic_year, created_at, updated_at
`

type UpdateContestantParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Birthday       pgtype.Date `json:"birthday"`
	NicOrStudentID string      `json:"nic_or_student_id"`
	PhotoUrl       *string     `json:"photo_url"`
	Gender         *string     `json:"gender"`
	AcademicYear   *string     `json:"academic_year"`
}

type UpdateContestantRow struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	BirthdayText   interface{}        `json:"birthday_text"`
	NicOrStudentID string             `json:"nic_or_student_id"`
	PhotoUrl       *string            `json:"photo_url"`
	Gender         *string            `json:"gender"`
	AcademicYear   *string            `json:"academic_year"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateContestant(ctx context.Context, arg UpdateContestantParams) (UpdateContestantRow, error) {
	row := q.db.QueryRow(ctx, updateContestant,
		arg.ID,
		arg.Name,
		arg.Birthday,
		arg.NicOrStudentID,
		arg.PhotoUrl,
		arg.Gender,
		arg.AcademicYear,
	)
	var i UpdateContestantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BirthdayText,
		&i.NicOrStudentID,
		&i.PhotoUrl,
		&i.Gender,
		&i.AcademicYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
