// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contestant struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	DateOfBirth  pgtype.Date        `json:"date_of_birth"`
	PhotoUrl     *string            `json:"photo_url"`
	Gender       *string            `json:"gender"`
	AcademicYear *string            `json:"academic_year"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Semester     *string            `json:"semester"`
	Nic          *string            `json:"nic"`
	StudentID    *string            `json:"student_id"`
}
