// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Contestant struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Birthday       pgtype.Date        `json:"birthday"`
	NicOrStudentID string             `json:"nic_or_student_id"`
	PhotoUrl       *string            `json:"photo_url"`
	Gender         *string            `json:"gender"`
	AcademicYear   *string            `json:"academic_year"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
