// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcgen

import (
	"context"
)

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT firebase_uid, email, display_name, photo_url, role, created_at, updated_at
FROM users
WHERE firebase_uid = $1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllUsers = `-- name: ListAllUsers :many
SELECT firebase_uid, email, display_name, photo_url, role, created_at, updated_at
FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.FirebaseUid,
			&i.Email,
			&i.DisplayName,
			&i.PhotoUrl,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, updated_at = NOW()
WHERE firebase_uid = $1
RETURNING firebase_uid, email, display_name, photo_url, role, created_at, updated_at
`

type UpdateUserRoleParams struct {
	FirebaseUid string `json:"firebase_uid"`
	Role        string `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.FirebaseUid, arg.Role)
	var i User
	err := row.Scan(
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (firebase_uid, email, display_name, photo_url, role)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (firebase_uid) DO UPDATE SET
    email        = EXCLUDED.email,
    display_name = EXCLUDED.display_name,
    photo_url    = EXCLUDED.photo_url,
    role         = EXCLUDED.role,
    updated_at   = NOW()
RETURNING firebase_uid, email, display_name, photo_url, role, created_at, updated_at
`

type UpsertUserParams struct {
	FirebaseUid string  `json:"firebase_uid"`
	Email       string  `json:"email"`
	DisplayName string  `json:"display_name"`
	PhotoUrl    *string `json:"photo_url"`
	Role        string  `json:"role"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.FirebaseUid,
		arg.Email,
		arg.DisplayName,
		arg.PhotoUrl,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.FirebaseUid,
		&i.Email,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
